build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/edustor/core:ci-$CI_PIPELINE_ID .
    - docker push registry.gitlab.com/edustor/core:ci-$CI_PIPELINE_ID

deploy:
  image: docker
  stage: deploy
  only:
    - master
  script:
    - mkdir -p /root/.docker
    - curl -sSL https://wutiarn.keybase.pub/swarm/ca.pem > /root/.docker/ca.pem
    - curl -sSL https://wutiarn.keybase.pub/swarm/cert.pem > /root/.docker/cert.pem
    - echo ${DOCKER_KEY} | base64 -d > /root/.docker/key.pem
    - export DOCKER_HOST=swarm.wutiarn.ru:2376
    - export DOCKER_TLS_VERIFY=1
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker service update --with-registry-auth --image registry.gitlab.com/edustor/core:ci-$CI_PIPELINE_ID sw0_edustor-core