#build:
#  stage: build
#  image: docker:latest
#  services:
#    - docker:dind
#  script:
#    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
#    - docker build -t registry.gitlab.com/edustor/core:ci-$CI_PIPELINE_ID .
#    - docker push registry.gitlab.com/edustor/core:ci-$CI_PIPELINE_ID

deploy:
  image: docker
  stage: deploy
  only:
    - master
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - curl -sSL ${CA_URL} > /root/.docker/ca.pem
    - curl -sSL ${CERT_URL} > /root/.docker/cert.pem
    - echo ${DOCKER_KEY} | base64 -d > /root/.docker/key.pem
    - DOCKER_HOST=swarm.wutiarn.ru:2376
      DOCKER_TLS_VERIFY=1
      docker service update --with-registry-auth --image registry.gitlab.com/edustor/core:ci-$CI_PIPELINE_ID sw0_edustor-core