build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/edustor/core:ci-$CI_PIPELINE_ID .
    - docker push registry.gitlab.com/edustor/core:ci-$CI_PIPELINE_ID