build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/edustor/core:ci-$CI_PIPELINE_ID .
    - docker push registry.gitlab.com/edustor/core:ci-$CI_PIPELINE_ID

deploy:
  image: quay.io/wutiarn/docker-deployer
  stage: deploy
  only:
    - master
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - DOCKER_HOST=swarm.wutiarn.ru:2376
      DOCKER_TLS_VERIFY=1
      CA_URL=https://wutiarn.keybase.pub/swarm/ca.pem
      CERT_URL=https://wutiarn.keybase.pub/swarm/cert.pem
      docker service update --with-registry-auth --image registry.gitlab.com/edustor/core:ci-$CI_PIPELINE_ID sw0_edustor-core
