build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u="edustor+gitlabci" -p="$REGISTRY_PASSWORD" quay.io
    - docker build -t quay.io/edustor/core:ci-$CI_PIPELINE_ID .
    - docker tag quay.io/edustor/core:ci-$CI_PIPELINE_ID quay.io/edustor/core:latest
    - docker push quay.io/edustor/core:ci-$CI_PIPELINE_ID
    - docker push quay.io/edustor/core:latest

deploy:
  image: docker
  stage: deploy
  only:
    - master
  script:
    - mkdir -p /root/.docker
    - curl -sSL https://wutiarn.keybase.pub/swarm/ca.pem > /root/.docker/ca.pem
    - curl -sSL https://wutiarn.keybase.pub/swarm/cert.pem > /root/.docker/cert.pem
    - echo ${SWARM_KEY} | base64 -d > /root/.docker/key.pem
    - export DOCKER_HOST=swarm.wutiarn.ru:2376
    - export DOCKER_TLS_VERIFY=1
    - docker login -u="edustor+gitlabci" -p="$REGISTRY_PASSWORD" quay.io
    - docker service update --with-registry-auth --image quay.io/edustor/core:ci-$CI_PIPELINE_ID sw0_edustor-core