variables:
  IMAGE_NAME: quay.io/edustor/core

build:
  stage: build
  image: docker:latest
  services:
    - quay.io/wutiarn/docker-dind-experimental
  variables:
    DOCKER_HOST: quay.io__wutiarn__docker-dind-experimental:2375
  script:
    - docker version
    - mkdir -p /root/.docker
    - echo $DOCKER_CONFIG > /root/.docker/config.json
    - docker login -u="edustor+gitlabci" -p="$REGISTRY_PASSWORD" quay.io
    - docker build -t $IMAGE_NAME:ci-$CI_PIPELINE_ID --squash .
    - docker tag $IMAGE_NAME:ci-$CI_PIPELINE_ID $IMAGE_NAME:latest
    - docker push $IMAGE_NAME:ci-$CI_PIPELINE_ID
    - docker push $IMAGE_NAME:latest

deploy:
  image: docker
  stage: deploy
  only:
    - master
  variables:
    SWARM_CA_URL: https://wutiarn.keybase.pub/swarm/ca.pem
    SWARM_CERT_URL: https://wutiarn.keybase.pub/swarm/cert.pem
  script:
    - mkdir -p /root/.docker
    - curl -sSL $SWARM_CA_URL > /root/.docker/ca.pem
    - curl -sSL $SWARM_CERT_URL > /root/.docker/cert.pem
    - echo $DOCKER_CONFIG > /root/.docker/config.json
    - echo ${DOCKER_KEY} > /root/.docker/key.pem
    - export DOCKER_HOST=swarm.wutiarn.ru:2376
    - export DOCKER_TLS_VERIFY=1
    - docker service update --with-registry-auth --image $IMAGE_NAME:ci-$CI_PIPELINE_ID sw0_edustor-core