build_image:
  image: docker:git
  stage: build
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/wutiarn/edustor .
    - docker push registry.gitlab.com/wutiarn/edustor:latest
    - docker images
    - docker history registry.gitlab.com/wutiarn/edustor
  only:
    - master

deploy:
  image: alpine
  stage: deploy
  script:
    - apk add -U wget
    - wget $DEPLOY_TRIGGER_URL -T 1800 -O - --content-on-error
  only:
    - master