stages:
  - test
  - upload
  - deploy

test_build:
  image: docker:git
  stage: test
  services:
    - docker:dind
  script:
    - docker build -t registry.gitlab.com/edustor/core .
  except:
    - master

build_homeserver_image:
  image: docker:git
  stage: upload
  environment: homeserver
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/edustor/core:homeserver .
    - docker push registry.gitlab.com/edustor/core:homeserver
    - docker images
    - docker history registry.gitlab.com/edustor/core:homeserver
  only:
    - master

deploy:
  image: alpine
  stage: deploy
  environment: homeserver
  script:
    - apk add -U wget
    - wget $DEPLOY_TRIGGER_URL -T 1800 -O - --content-on-error
  only:
    - master