version: '2'
services:
  web:
    build: .
    ports:
     - "80:8080"
    links:
      - mongo
    restart: unless-stopped
  mongo:
    image: mongo:3.2
    volumes:
      - /mnt/edustor:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped