version: '2'
services:
  mongo:
    image: mongo:3.2
    volumes:
      - mongo:/data/db
    ports:
      - "27017:27017"
  rabbit:
    image: rabbitmq:3-management
    ports:
      - 4369:4369
      - 5671:5671
      - 5672:5672
      - 15671:15671
      - 15672:15672
      - 25672:25672

volumes:
  mongo:
