spring:
  http:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb
  datasource:
      url: jdbc:postgresql://postgres:5432/edustor_core
      username: postgres
  jpa:
      hibernate:
        ddl-auto: update
      generate-ddl: true
flyway:
  validate-on-migrate: false
