version: 2
jobs:
  build:
    working_directory: ~/edustor-core
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker version
          docker info